version: "3.3"

services:
  nginx:
    image: nginx:1.19.2-alpine
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    # environment:
    #   - NGINX_HOST=foobar.com
    #   - NGINX_PORT=80
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  client:
    restart: always
    container_name: client
    build:
      context: ./client/
    command: yarn start
    volumes:
      - ./client/:/app/client
      - /app/client/node_modules
    ports:
      - "3000:3000"

  server:
    restart: always
    container_name: server
    build:
      context: ./server/
    command: node index.js
    volumes:
      - ./server/:/app/server
      - /app/server/node_modules
    ports:
      - "5000:5000"
